#!/bin/sh
### BEGIN INIT INFO
# Provides:          reposerver
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the Reposerver
# Description:       A simple Flask application server.
### END INIT INFO

# -- Configurações --
DIR="/opt/reposerver"
USER="root" # Ou um usuário dedicado se preferir
NAME="reposerver"
VENV_DIR="$DIR/venv"
GUNICORN_EXEC="$VENV_DIR/bin/gunicorn"
APP_MODULE="run:app"
HOST="0.0.0.0"
PORT="5000"
WORKERS=4
WORKER_CLASS="eventlet"
PIDFILE="/var/run/$NAME.pid"
LOGFILE="/var/log/$NAME.log"

# -- Funções --
. /lib/lsb/init-functions

start() {
    if [ -f $PIDFILE ]; then
        log_daemon_msg "$NAME is already running"
        return 1
    fi
    log_daemon_msg "Starting $NAME"
    cd $DIR || return 1
    start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile \
        --background --chuid $USER --exec $GUNICORN_EXEC -- \
        --bind $HOST:$PORT \
        --workers $WORKERS \
        --worker-class $WORKER_CLASS \
        --log-file $LOGFILE \
        $APP_MODULE
    log_end_msg $?
}

stop() {
    if [ ! -f $PIDFILE ]; then
        log_daemon_msg "$NAME is not running"
        return 1
    fi
    log_daemon_msg "Stopping $NAME"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 5
    rm -f $PIDFILE
    log_end_msg $?
}

status() {
    status_of_proc -p $PIDFILE "$GUNICORN_EXEC" "$NAME" && exit 0 || exit $?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
